
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

//import "gameObj.sol";

 interface gameObjInt {
 
     function catchAtk(int atkPwr, address target) external returns (bool);


 }